// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbblsqogkolqwrpravhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYmxzcW9na29scXdycHJhdmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NzMwMTgsImV4cCI6MjA2NTM0OTAxOH0._261kEPWQUr6vu77hMrm5KbZdUdS2ujnEMe9efjH0tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);